### ISSUE TITLE
something wrong with the output

### ISSUE THREAD

**Issue by liyuelan** [nselem/bigscape-corason#14]
Hello, 

I am running 4w BGCs, which which are supposed to be the same type, so I want to use --mix in case.  This is my code:

"python /mnt/sdb/lyl/conda/lib/python3.7/site-packages/BiG-SCAPE/bigscape.py --inputdir=/mnt/sdb/lyl/20230316_bigscape/input_42456 --outputdir=/mnt/sdb/lyl/20230316_bigscape/output --pfam_dir=/mnt/sdb/lyl/pfam_database --cores 40 --
mibig --include_singletons --mix --no_classify --verbose > run_bigscape_20230327.log &"

but I found there was something wrong. BigSCAPE was just stopped without cluster annotations. I checked the log file:

"  Mix (44957 BGCs)
  Calculating all pairwise distances
generate_network took 29769.790 seconds
   Removing 2351 non-relevant MIBiG BGCs
  Writing output files
  Calling Gene Cluster Families"

And this is the outputfile in /output/network_files/2023-03-27_11-48-16_hybrids_glocal/mix/

![图片](https://user-images.githubusercontent.com/127102466/228462046-3f0205f3-d313-40ca-99e3-57b81999635f.png)

I don't know what's wrong. I don't know if I misused the --no_classify, or if 4w inputfiles are too large to use bigscape? 

Thank you!

**Comment by jorgecnavarrom** [comment]
The `--no_classify` parameter is correct as you also used `--mix`. I think the size of the input data might be the issue. Did you see any other text (in the log file or the terminal) after the "Calling Gene Cluster Families" lines?
One possible option would be to lower the number of cores, as large data structures are passed to each core. The run should take less time if you re-use the output folder, which contains a lot of pre-processed data

**Comment by liyuelan** [comment]
Thank you for quick response.  

This time I did as this:

python /mnt/sdb/lyl/conda/lib/python3.7/site-packages/BiG-SCAPE/bigscape.py --inputdir=/mnt/sdb/lyl/20230316_bigscape/input_42456 --outputdir=/mnt/sdb/lyl/20230316_bigscape/output --pfam_dir=/mnt/sdb/lyl/pfam_database --cores 20 --
mibig --include_singletons --verbose

I found that there are many run errors of python files in path /python3.7/multiprocessing/

like this:

Traceback (most recent call last):
  File "/mnt/sdb/lyl/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/mnt/sdb/lyl/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/sdb/lyl/conda/lib/python3.7/multiprocessing/pool.py", line 131, in worker
    wrapped))
  File "/mnt/sdb/lyl/conda/lib/python3.7/multiprocessing/pool.py", line 87, in __str__
    self.exc)
MemoryError

it is a MemoryError

![图片](https://user-images.githubusercontent.com/127102466/228708167-5f6edb4d-c1e2-4aab-b3e9-373c5b31d6b2.png)

I will deal with it.
