### ISSUE TITLE
Error with `pram_dir`

### ISSUE THREAD

**Issue by tiagolbiotech** [nselem/bigscape-corason#7]
Dear Dr Jorge,

I have these pfam files (Pfam-A.hmm, Pfam-A.hmm.h3f, Pfam-A.hmm.h3i, Pfam-A.hmm.h3m, Pfam-A.hmm.h3p) located at the same directory as the bigscape.py file. I was able to run BiG-SCAPE in March without issues. I'm running basically the same files with the same pfam files using the command below:

```
python bigscape.py --pfam_dir ./ -i /Users/tiagoferreiraleao/Dropbox/tiago-NAS/BioGeneClassifier/antismash_results_all/ -o /Volumes/TFL210426/bigscape/bigscape_outputs_220503_1898samples/ -c 8 --include_singletons
```

However, this time I'm getting the following error:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/tiagoferreiraleao/anaconda3/envs/bigscape/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/tiagoferreiraleao/anaconda3/envs/bigscape/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Volumes/TFL210426/bigscape/BiG-SCAPE/bigscape.py", line 1223, in run_hmmalign
    hmmfetch_pars = ["hmmfetch", os.path.join(pfam_dir,"Pfam-A.hmm.h3m"), domain_base]
NameError: name 'pfam_dir' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bigscape.py", line 2821, in <module>
    launch_hmmalign(cores, domain_sequence_list)
  File "bigscape.py", line 489, in _wrap
    ret = funct(*args)
  File "bigscape.py", line 1215, in launch_hmmalign
    pool.map(run_hmmalign, domain_sequence_list)
  File "/Users/tiagoferreiraleao/anaconda3/envs/bigscape/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/tiagoferreiraleao/anaconda3/envs/bigscape/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
NameError: name 'pfam_dir' is not defined
```

I cloned the BiG-SCAPE repository again (from here https://git.wageningenur.nl/medema-group/BiG-SCAPE) and created a fresh environment, installing all required dependencies but it still did not work. Is that something you could help me with?

Thanks in advance,
Tiago.

**Comment by jorgecnavarrom** [comment]
Hi Tiago

Not sure what could be happening... We had a case like this last December (https://github.com/nselem/bigscape/issues/6), and at the end the solution was to install the dependencies using a conda environment installed using the yml file.

BiG-SCAPE is now also available through bioconda directly (i.e. instead of only installing the requirements, this version also includes BiG-SCAPE). I tried it yesterday and it worked, so that could be another option.

(as a small note: we have moved the official repository of BiG-SCAPE to https://github.com/medema-group/BiG-SCAPE)

**Comment by tiagolbiotech** [comment]
Hello Dr Jorge,

Thank you for your instructions. I followed them and used condo for installation of the dependencies and also bigscape. However, now I got a different error, please see below:

```
bigscape.py --pfam_dir /Volumes/TFL210426/bigscape/pfam_files/ -i /Users/tiagoferreiraleao/Dropbox/tiago-NAS/BioGeneClassifier/antismash_results_all/ -o /Volumes/TFL210426/bigscape/bigscape_outputs_220504_1898samples/ -c 8 --include_singletons
File with list of anchor domains not found


   - - Processing input files - -
 Including files with one or more of the following strings in their filename: 'cluster', 'region'
 Skipping files with one or more of the following strings in their filename: 'final'

Importing GenBank files
  Warning: unknown product 'prodigiosin'
  Warning: unknown product 'thioamitides'
  Warning: unknown product 'thioamitides'
  Warning: unknown product 'prodigiosin'
  Warning: unknown product 'prodigiosin'
  Warning: unknown product 'prodigiosin'
  Warning: unknown product 'prodigiosin'
  Warning: unknown product 'prodigiosin'
  Warning: unknown product 'prodigiosin'
  Warning: unknown product 'thioamitides'
  Warning: unknown product 'redox-cofactor'
  Warning: unknown product 'thioamitides'
  Warning: unknown product 'thioamitides'
  Warning: unknown product 'thioamitides'
  Warning: unknown product 'thioamitides'
  Warning: unknown product 'thioamitides'
  Warning: unknown product 'thioamitides'

 Starting with 1757 files
 Files that had its sequence extracted: 1757

Creating output directories

Trying threading on 8 cores

Predicting domains using hmmscan
 Predicting domains for 1757 fasta files
 Finished generating domtable files.

Parsing hmmscan domtable files
 Processing 1757 domtable files
  No domains where found in BGC0001181.1.region001.domtable. Removing it from further analysis
  No domains where found in BGC0001481.1.region001.domtable. Removing it from further analysis
  No domains where found in BGC0000683.1.region001.domtable. Removing it from further analysis
  No domains where found in BGC0001601.1.region001.domtable. Removing it from further analysis
 New domain sequences to be added; cleaning domains folder
 Finished generating pfs and pfd files.

Processing domains sequence files
 Adding sequences to corresponding domains file
 Reading the ordered list of domains from the pfs files
 Creating arrower-like figures for each BGC
  Parsing hmm file for domain information
    Done
  Domains colors file was not found. An empty file will be created
  Reading BGC information and writing SVG
 Finished creating figures


   - - Calculating distance matrix - -
Performing multiple alignment of domain sequences

 Using hmmalign
launch_hmmalign took 472.620 seconds
 Trying to read domain alignments (*.algn files)
Traceback (most recent call last):
  File "/Users/tiagoferreiraleao/anaconda3/envs/bigscape/bin/bigscape.py", line 2860, in <module>
    dir_util.copy_tree(os.path.join(os.path.dirname(os.path.realpath(__file__)), "html_template", "output"), output_folder)
  File "/Users/tiagoferreiraleao/anaconda3/envs/bigscape/lib/python3.6/distutils/dir_util.py", line 124, in copy_tree
    "cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree '/Users/tiagoferreiraleao/anaconda3/envs/bigscape/bin/html_template/output': not a directory
```

**Comment by jorgecnavarrom** [comment]
It seems like something went wrong with the installation of BiG-SCAPE? In my case, that folder is at `/home/jorge/miniconda3/envs/bigscape_conda/lib/python3.6/site-packages/BiG-SCAPE/html_template/output/` 

> I followed them and used condo for installation of the dependencies and also bigscape

Just to confirm, you installed BiG-SCAPE using `conda create -n [your name] -c bioconda bigscape`?

**Comment by tiagolbiotech** [comment]
Correct, I used `conda create -n bigscape -c bioconda bigscape` and `source activate bigscape` and installed the dependencies (some were already installed). Althogh, I still get the error:

```
 Using hmmalign
launch_hmmalign took 266.845 seconds
 Trying to read domain alignments (*.algn files)
Traceback (most recent call last):
  File "/Users/tiagoferreiraleao/anaconda3/envs/bigscape/bin/bigscape.py", line 2860, in <module>
    dir_util.copy_tree(os.path.join(os.path.dirname(os.path.realpath(__file__)), "html_template", "output"), output_folder)
  File "/Users/tiagoferreiraleao/anaconda3/envs/bigscape/lib/python3.6/distutils/dir_util.py", line 124, in copy_tree
    "cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree '/Users/tiagoferreiraleao/anaconda3/envs/bigscape/bin/html_template/output': not a directory
```

**Comment by jorgecnavarrom** [comment]
> and installed the dependencies (some were already installed)

Well, in theory the conda installation should take care of all dependencies, so installing them manually shouldn't be necessary. I don't think that's the issue here, though...

Just to check, what was the version of BiG-SCAPE installed by conda (i.e. `conda list | grep bigscape`)? Version 1.1.4 should work, but we did have a few issues with 1.1.3 in conda

**Comment by tiagolbiotech** [comment]
I did it again only using `conda create -n bigscape -c bioconda bigscape` and still get the same error. I get version 1.1.4:
```
(bigscape) Tiagos-MacBook-Pro:bigscape tiagoferreiraleao$ conda list | grep bigscape
# packages in environment at /Users/tiagoferreiraleao/anaconda3/envs/bigscape:
bigscape                  1.1.4              pyhdfd78af_0    bioconda
```

**Comment by tiagolbiotech** [comment]
I don't have the folder `html_template` folder inside `/Users/tiagoferreiraleao/anaconda3/envs/bigscape/bin/`

**Comment by tiagolbiotech** [comment]
It worked! I copied the missing folder (`html_template`) from here https://git.wageningenur.nl/medema-group/BiG-SCAPE and it run successfully! Thank you for you help!

**Comment by jorgecnavarrom** [comment]
That's great to hear Tiago!
Still puzzles me as to what may be happening, because I couldn't replicate it on my machine.
I'll keep this issue open in case we figure out what was going on
