### ISSUE TITLE
BiopythonDeprecationWarning

### ISSUE THREAD

**Issue by Gahyeon-K** [nselem/bigscape-corason#8]
Error1: anaconda3/envs/bigscape/lib/python3.10/site-packages/Bio/SubsMat/__init__.py:126: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.

Error2:  Warning: unknown product 'redox-cofactor'

Question3. When I opened 'index.html' from the output file, nothing was to be seen.

Question4. Is version 1.1.2 (2021-06-03) the latest?

Thank you.

**Comment by Caiyulu-818** [comment]
i also meet the Warning: anaconda3/envs/bigscape/lib/python3.10/site-packages/sklearn/cluster/_affinity_propagation.py:144: UserWarning: All samples have mutually equal similarities. Returning arbitrary cluster center(s).
All samples have mutually equal similarities this 

then the task was killed ~
is there any problems?
:

**Comment by Caiyulu-818** [comment]
FutureWarning)
/home/ec2-user/miniconda3/envs/bigscape/lib/python3.6/site-packages/sklearn/cluster/_affinity_propagation.py:244: ConvergenceWarning: Affinity propagation did not converge, this model will not have any cluster centers.
  "will not have any cluster centers.", ConvergenceWarning)
generate_network took 187.475 seconds
   Writing output files
  Calling Gene Cluster Families
  Cutoff: 0.3
Traceback (most recent call last):
  File "/application/BiG-SCAPE/bigscape.py", line 3286, in <module>
    htmlFolder=network_html_folder)
  File "/application/BiG-SCAPE/bigscape.py", line 1771, in clusterJsonBatch
    clanLabels = [familyIdx[exemplarsClans[labelsClans[i]]] for i in range(len(familyIdx))]
  File "/application/BiG-SCAPE/bigscape.py", line 1771, in <listcomp>
    clanLabels = [familyIdx[exemplarsClans[labelsClans[i]]] for i in range(len(familyIdx))]
IndexError: list index out of range

out of range 
the number of bgc of my project is 70000+ ? is the number out of range which cause the problem?

**Comment by cmandreani** [comment]
Hi @jorgecnavarrom and @Caiyulu-818, 

I had the same problem today when running bigscape with anaconda3. With [docker](https://bigscape-corason.secondarymetabolites.org/tutorial/index.html) it worked fine, though.

Hope it helps.

Cheers.

```
/opt/anaconda3/envs/bigscape/lib/python3.9/site-packages/sklearn/cluster/_affinity_propagation.py:250: ConvergenceWarning: Affinity propagation did not converge, this model will not have any cluster centers.
  warnings.warn(
Traceback (most recent call last):
  File "/opt/anaconda3/envs/bigscape/BiG-SCAPE/bigscape.py", line 3283, in <module>
    family_data = clusterJsonBatch(BGC_classes[bgc_class], pathBase, bgc_class,
  File "/opt/anaconda3/envs/bigscape/BiG-SCAPE/bigscape.py", line 1771, in clusterJsonBatch
    clanLabels = [familyIdx[exemplarsClans[labelsClans[i]]] for i in range(len(familyIdx))]
  File "/opt/anaconda3/envs/bigscape/BiG-SCAPE/bigscape.py", line 1771, in <listcomp>
    clanLabels = [familyIdx[exemplarsClans[labelsClans[i]]] for i in range(len(familyIdx))]
IndexError: list index out of range

(...) #runs ok
/opt/anaconda3/envs/bigscape/lib/python3.9/site-packages/sklearn/cluster/_affinity_propagation.py:250: ConvergenceWarning: Affinity propagation did not converge, this model will not have any cluster centers.
  warnings.warn(
Traceback (most recent call last):
  File "/opt/anaconda3/envs/bigscape/BiG-SCAPE/bigscape.py", line 3283, in <module>
    family_data = clusterJsonBatch(BGC_classes[bgc_class], pathBase, bgc_class,
  File "/opt/anaconda3/envs/bigscape/BiG-SCAPE/bigscape.py", line 1771, in clusterJsonBatch
    clanLabels = [familyIdx[exemplarsClans[labelsClans[i]]] for i in range(len(familyIdx))]
  File "/opt/anaconda3/envs/bigscape/BiG-SCAPE/bigscape.py", line 1771, in <listcomp>
    clanLabels = [familyIdx[exemplarsClans[labelsClans[i]]] for i in range(len(familyIdx))]
IndexError: list index out of range
```
