### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by devarajarun** [nselem/bigscape-corason#9]
I'm looking for clustering BGCs in specific genera, and I have 1733 regions from antismash results in total. I received this error when I attempted to run bigscape for all regions. So what could be the reason ?

Traceback (most recent call last):
  File "bigscape.py", line 3067, in <module>
    clanCutoff=options.clan_cutoff, htmlFolder=network_html_folder)
  File "bigscape.py", line 1771, in clusterJsonBatch
    clanLabels = [familyIdx[exemplarsClans[labelsClans[i]]] for i in range(len(familyIdx))]
  File "bigscape.py", line 1771, in <listcomp>
    clanLabels = [familyIdx[exemplarsClans[labelsClans[i]]] for i in range(len(familyIdx))]
IndexError: list index out of range

**Comment by jorgecnavarrom** [comment]
It may be due to the scikit-learn version. 

See this thread in BiG-SCAPE's repository: https://github.com/medema-group/BiG-SCAPE/issues/2
